import requests

urls = [  "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Ivana%20Spagna%20-%20Easy%20Lady.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Jackson%20Browne%20-%20Somebody's%20Baby%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Jan%20Hammer%20-%20Crockett's%20Theme.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Jay-Jay%20Johnson%20-%20Rush%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Jazzdauren - Дарите женщинам цветы .mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Jeanette - ¿Por qué te vas#.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Jennifer%20Paige%20-%20Crush.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Jennifer%20Rush%20-%20I%20Come%20Undone.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Jermaine%20Jackson%2C%20Pia%20Zadora%20-%20When%20the%20Rain%20Begins%20to%20Fall.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Jessica%20Jay%20-%20Casablanca.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Jigsaw%20-%20Sky%20High%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Joan%20Jett%20%26%20the%20Blackhearts%20-%20I%20Hate%20Myself%20for%20Loving%20You.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Joan%20Osborne%20-%20One%20Of%20Us%20-%20Short%20Version.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Joe%20Bonamassa%20-%20How%20deep%20this%20river%20runs%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Joe%20Cocker%20-%20My%20Fathers%20Son.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Joe%20Cocker%20-%20Unchain%20My%20Heart.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Joe%20Cocker%20-%20With%20A%20Little%20Help%20From%20My%20Friends%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/John%20Davis%20-%20Who%20do%20you%20love%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/John%20Farnham%20-%20You're%20the%20Voice.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/John%20Lennon%20-%20Imagine%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/John%20Lennon%20-%20Stand%20By%20Me%20-%20Remastered%202010.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/John%20Lennon%20-%20Woman.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/John%20Waite%20-%20Missing%20you%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Johnny%20Cash%20-%20Personal%20Jesus.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Johnny%20Hates%20-%20Shattered%20Dreams%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Johnny%20Nash%20-%20I%20Can%20See%20Clearly%20Now%20-%20Edit.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Johnny%20Nash%20-%20I%20can%20see%20clearly%20now%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Jon%20Astley%20-%20Jane's%20Getting%20Serious%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Jon%20Astley%20-%20The%20menu.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Jon%20Bon%20Jovi%20-%20Blaze%20Of%20Glory%20-%20From%20%23Young%20Guns%20II%23%20Soundtrack.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Jon%20Hopkins%20-%20Afterlife%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Jon%20Secada%20-%20Just%20another%20day.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Josep%20Porto%20-%20Nova%20Esplendor.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Journey%20-%20Lights%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Joy%20Division%20-%20Love%20will%20tear%20us%20apart.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Judas%20Priest%20-%20Breaking%20The%20law%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Judas%20Priest%20-%20You've%20Got%20Another%20Thing%20Coming.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Julie%20London%20-%20Cry%20Me%20A%20River.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Julie%20London%20-%20When%20I%20fall%20in%20love%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/June%20Grand%20-%20Shy%20girl%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Jurij Antonov - Зеркало .mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/K.Barre%20-%20Right%20by%20the%20Moon%20-%20Special%20Dance%20Remix.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/KISS%20-%20I%20Was%20Made%20For%20Lovin'%20You.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/KISS%20-%20Reason%20To%20Live.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/KISS%20-%20Rock%20And%20Roll%20All%20Nite.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kaada%20-%20Hardangervidda.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kaleida%20-%20Take%20me%20to%20the%20river%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kamar - Человек Грамм.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kano%20-%20Another%20Life%20-%20Original.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kansas%20-%20Dust%20in%20the%20Wind%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Karaoke%20Diamonds%20-%2018%20Till%20I%20Die%20-%20Originally%20Performed%20By%20Bryan%20Adams.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Karen%20Souza%20-%20Personal%20Jesus.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kate%20Bush%20-%20Army%20Dreamers%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kate%20Bush%20-%20Running%20up%20that%20hill.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Katie%20Melua%20-%20Nine%20Million%20Bicycles%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/KatriX%2C%20Doron%20Biton%20-%20Karnaval%20Balev.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Katya Celebrine & Maxim Nazarov- Светотень.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kelly%20Brown%20-%20Only%20you%20can%20(%20you%20make%20me%20feel).mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kelly%20Brown%20-%20Only%20you%20can%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Ken%20Laszlo%20-%20Hey%20Hey%20Guy.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Ken%20Laszlo%20-%20Tonight.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kenya%20Grace%20-%20Strangers%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Khaled - Aïcha - Version Mixte.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Killing%20Joke%20-%20Eighties.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kim%20Carnes%20-%20Bette%20Davis%20Eyes.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kim%20Wilde%20-%20Cambodia%20-%20Single%20Version.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kim%20Wilde%20-%20You%20Came%20-%20Single%20Version.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kim%20Wilde%20-%20You%20keep%20me%20Hanging%20On.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/King%20Harvest%20-%20Dancing%20in%20the%20Moonlight%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kinobe%20ft.%20Ben%20%26%20Jason%20-%20Slip%20into%20Something.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kiss - God Gave Rock ‘n’ Roll To You II.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kiss%20-%20Hide%20your%20heart%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kix%20-%20Don't%20Close%20Your%20Eyes.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Klavdia Petrivna - Знайди мене .mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Klavdia Petrivna - Я щаслива .mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kool%20%26%20The%20Gang%20-%20Fresh.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Koop%20-%20Koop%20Island%20Blues.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Korine%20-%20Fate.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Koto%20-%20Visitors%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kylie%20Minogue%20-%20Can't%20get%20you%20out%20of%20my%20head.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kylie%20Minogue%20-%20Confide%20in%20me%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Kylie%20Minogue%20-%20Fever.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/LA%20BOUM%20-%20Reality%20-%20Richard%20Sanderson%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/LENA%20-%20Run%20to%20me%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/LES%20McKEOWN%20-%20It's%20a%20game%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/LP%20-%20Lost%20on%20You.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/La%20Roux%20-%20Cover%20my%20eyes.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/La%20Roux%20-%20I'm%20not%20your%20toy.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/La%20Roux%20-%20In%20for%20the%20kill.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/La%20Roux%20-%20Let%20Me%20Down%20Gently.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/La%20Roux%20-%20Quicksand%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/La%20Roux%2C%20Beni%20-%20Quicksand%20-%20Beni's%20Sinking%20at%201.56%20Mix.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/La%20Roux%2C%20GAMPER%20%26%20DADONI%20-%20Bulletproof.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Laid%20Back%20-%20Bakerman.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Laid%20Back%20-%20High%20Society%20girl%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Laid%20Back%20-%20Sunshine%20Reggae.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Lamb%20-%20Trans%20Fatty%20Acid.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Lana%20Del%20Rey%20-%20Summertime%20Sadness.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Las%20Ketchup%20-%20The%20Ketchup%20Song.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Laura%20Branigan%20-%20Self%20Control.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Le%20Click%20-%20Tonight%20Is%20The%20Night.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Led%20Zeppelin%20-%20All%20My%20Love%20-%20Remaster.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Leonard%20Cohen%20-%20Dance%20me%20to%20the%20beat%20me%20of%20love%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Leonard%20Cohen%20-%20In%20my%20secret%20life%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Level%2042%20-%20Lessons%20In%20Love.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Linda%20Jo%20Russo%20-%20You're%20my%20first%2C%20you're%20my%20last%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Lionel%20Richie%20-%20Say%20you%2C%20say%20me.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Lita%20Ford%2C%20Ozzy%20Osbourne%20-%20Close%20My%20Eyes%20Forever.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Little%20Big%20-%20FARADENZA%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Little%20Big%20-%20Go%20Bananas.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Little%20Big%20-%20Hypnodancer.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Little%20Big%20-%20Skibidi.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Lobo%20-%20I'd%20Love%20you%20to%20want%20me%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Loft%20-%20Free%20me.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/London%20Boys%20-%20Harlem%20Desire.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/London%20Boys%20-%20Love%20Train%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/LondonBeat%20-%20I've%20been%20thinking%20about%20you%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Lou%20Doillon%20-%20ICU.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Love%20Fool%20-%20The%20Cardigans%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Love%20and%20Rockets%20-%20So%20Alive.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Lynyrd%20Skynyrd%20-%20Free%20Bird.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Lynyrd%20Skynyrd%20-%20Simple%20Man%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Madonna%20-%20Don't%20cry%20for%20me%20Argentina%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Madonna%20-%20Frozen%20.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Madonna%20-%20Into%20the%20Groove.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Madonna%20-%20La%20Isla%20Bonita.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Madonna%20-%20Like%20a%20Prayer.mp3",
            "https://raw.githubusercontent.com/ForSomeStrangeReason/part5/main/Madonna%20-%20Papa%20Don't%20Preach.mp3",             
]

for url in urls:
    filename = url.split("/")[-1]
    r = requests.get(url)
    with open(filename, "wb") as f:
        f.write(r.content)
